version: '3.8'

services:
  web:
    extends:
      file: ../../apps/web/docker-compose.dev.yml
      service: web
    depends_on:
      - api

  api:
    extends:
      file: ../../services/api/docker-compose.dev.yml
      service: api
    depends_on:
      - postgres

  worker:
    extends:
      file: ../../services/worker/docker-compose.dev.yml
      service: worker
    depends_on:
      - postgres

  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 