version: '3'
services:
  web:
    build:
      context: ../..
      dockerfile: docker/dev/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXT_TELEMETRY_DISABLED=1
      - WATCHPACK_POLLING=true
    command: sh -c "cd apps/web && pnpm dev"
    volumes:
      - ../../apps/web:/app/apps/web
      - /app/apps/web/node_modules
      - /app/apps/web/.next
