services:
  web:
    image: 65862070/freelancehub-web:v1.0.1
    container_name: web
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    command: >
      sh -c "pnpm add -D tailwindcss postcss autoprefixer &&
             npx tailwindcss init -p &&
             pnpm dev"
