version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: docker/dev/Dockerfile
    ports:
      - "4000:4000"
    volumes:
      - ./src:/app/src:rw
      - api_node_modules:/app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: freelancehub
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  api_node_modules:
