version: '3.8'

services:
  web:
    build:
      context: ../..
      dockerfile: docker/prod/web.Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - API_URL=http://api:4000
    depends_on:
      - api
    restart: unless-stopped

  api:
    build:
      context: ../..
      dockerfile: docker/prod/api.Dockerfile
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/freelancehub
    depends_on:
      - postgres
    restart: unless-stopped

  worker:
    build:
      context: ../..
      dockerfile: docker/prod/worker.Dockerfile
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/freelancehub
    depends_on:
      - postgres
    restart: unless-stopped

  postgres:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: freelancehub
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata: 