services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: 65862070/freelancehub-api:v1.0.1
    container_name: freelancehub-api
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules 